# channel locations. These override conda defaults, i.e., conda will
# search *only* the channels listed here, in the order given. Use "defaults" to
# automatically include all default channels. Non-url channels will be
# interpreted as binstar usernames (this can be changed by modifying the
# channel_alias key; see below).
channels:
  - defaults

# Alias to use for non-url channels used with the -c flag. Default is
# https://conda.binstar.org/

# channel_alias: https://your.repo/

# When the channel alias is binstar.org or an Anaconda Server GUI, this will
# use the binstar command line client (which can be installed with 'conda
# install binstar' to automatically add the token to the channel urls, so that
# you can see private packages). The default is True, but it is only enabled
# if the binstar command line client is installed and you are logged in
# ('binstar login').
# add_binstar_token: False

# Proxy settings: http://[username]:[password]@[server]:[port]
# proxy_servers:
#     http: http://user:pass@corp.com:8080
#     https: https://user:pass@corp.com:8080

# Disable ssl verification. The default is True.
# ssl_verify: False

# Directories in which environments are located. If this key is set, the root
# prefix envs dir is not used unless explicitly included. This key also
# determines where the package caches will be located. For each envs here,
# envs/.pkgs will be used as the pkgs cache, except for standard the envs
# directory in the root directory, for which the normal root_dir/pkgs is used.
# The CONDA_ENVS_PATH environment variable, which is a colon separated list,
# allows overwriting this setting here.
# envs_dirs:
#   - ~/my-envs
#   - /opt/anaconda/envs

# implies always using the --yes option whenever asked to proceed
always_yes: true

# disallow soft-linking (default is allow_softlinks: True,
#                        i.e. soft-link when possible)
# allow_softlinks: False

# change ps1 when using activate (default True)
changeps1: false

# use pip when listing packages (default True)
# use_pip: False

# binstar.org upload (not defined here means ask)
# binstar_upload: True
# do not upload binstar packages to the public channel (default True)
# binstar_personal: True

# when creating new environments add these packages by default
create_default_packages:
  - python
  - pip

# disallowed specification names
disallow:
  - anaconda

# show channel URLs when displaying what is going to be downloaded, and
# in conda list
show_channel_urls: true

# enable certain features to be tracked by default
# track_features:
#   - mkl

# Conda Build Options
conda-build:
  # Build output root directory. (default <CONDA_PREFIX>/conda-bld/, or
  # ~/conda-bld if you do not have write permissions to
  # <CONDA_PREFIX>/conda-bld) This can also be set with the CONDA_BLD_PATH
  # environment variable.
  root-dir: ~/conda-builds
solver: libmamba
