# Zsh configuration file for themes

# If no theme is specified, create a default setup
if test -n "$ZSH_THEME"; then
    export ZSH_THEME='agnoster'

# Setup for powerlevel9k
elif [ $ZSH_THEME -eq "powerlevel9k/powerlevel9k" ]; then
    POWERLEVEL9K_MODE="awesome_fotconfig"
    POWERLEVEL9K_FOLDER_ICON=""
    POWERLEVEL9K_HOME_SUB_ICON="$(print_icon "HOME_ICON")"
    POWERLEVEL9K_DIR_PATH_SEPARATOR=" $(print_icon "LEFT_SUBSEGMENT_SEPARATOR") "
    POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
    POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true
    POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='black'
    POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='178'
    POWERLEVEL9K_NVM_BACKGROUND='238'
    POWERLEVEL9K_NVM_FOREGROUND='green'
    POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='blue'
    POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND='015'
    POWERLEVEL9K_TIME_BACKGROUND='255'
    POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='245'
    POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'
    POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator context dir dir_writable vcs)
    POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs)
    POWERLEVEL9K_SHOW_CHANGESET=true
    
    # See V1grul config
fi
