#! /bin/zsh -
# Top level zshrc file

# Where are the dotfiles
export DOTPATH=$HOME/.dotfiles
# Define where the zsh folder is
export ZSHPATH=$DOTPATH/zsh
# Start by sourcing the common script
source $DOTPATH/shell/common.sh

# Source a framework setup
source $ZSHPATH/zshinit
